name: CastlesMirage1.20.1
version: '${project.version}'
main: com.mirage.castles.Castels
api-version: '1.20'
commands:
  getmenubook:
    description: "Получить книгу для открытия меню."
    usage: "/getmenubook"
    permission: castles.getmenubook
    depend: [Citizens]
